# Generated by Django 5.2.4 on 2025-08-06 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("screen_name", models.CharField(max_length=150, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("contributor", "Content Contributor"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "card_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContributorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_full_name", models.CharField(max_length=255)),
                ("show_name_public", models.BooleanField(default=False)),
                ("date_of_birth", models.DateField()),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("height", models.CharField(max_length=20)),
                ("weight", models.CharField(max_length=20)),
                ("shoe_size", models.CharField(max_length=10)),
                (
                    "skin_tone",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("dark", "Dark"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "hair_color",
                    models.CharField(
                        choices=[
                            ("blonde", "Blonde"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                            ("red", "Red"),
                            ("auburn", "Auburn"),
                            ("dirty_blonde", "Dirty Blonde"),
                            ("strawberry_blonde", "Strawberry Blonde"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "body_type_male",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("short_thin", "Short & Thin"),
                            ("short_broad", "Short & Broad"),
                            ("athletic", "Athletic/Average"),
                            ("tall_slim", "Tall & Slim"),
                            ("big_tall", "Big & Tall"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "body_type_female",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petite", "Petite"),
                            ("tall_slender", "Tall & Slender"),
                            ("athletic", "Athletic/Average"),
                            ("curvy", "Curvy"),
                            ("plus_size", "Plus Size"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributor_profile",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
