# Generated by Django 5.2.4 on 2025-08-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="card_details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="hair_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blonde", "Blonde"),
                    ("brown", "Brown"),
                    ("black", "Black"),
                    ("red", "Red"),
                    ("auburn", "Auburn"),
                    ("dirty_blonde", "Dirty Blonde"),
                    ("strawberry_blonde", "Strawberry Blonde"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="legal_full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="shoe_size",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="skin_tone",
            field=models.CharField(
                blank=True,
                choices=[("light", "Light"), ("medium", "Medium"), ("dark", "Dark")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
