# Generated by Django 5.2.4 on 2025-08-05 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="body_type_female",
        ),
        migrations.RemoveField(
            model_name="user",
            name="body_type_male",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hair_color",
        ),
        migrations.RemoveField(
            model_name="user",
            name="height",
        ),
        migrations.RemoveField(
            model_name="user",
            name="legal_full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="user",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="shoe_size",
        ),
        migrations.RemoveField(
            model_name="user",
            name="show_name_public",
        ),
        migrations.RemoveField(
            model_name="user",
            name="skin_tone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="state",
        ),
        migrations.RemoveField(
            model_name="user",
            name="weight",
        ),
        migrations.CreateModel(
            name="ContributorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_full_name", models.CharField(max_length=255)),
                ("show_name_public", models.BooleanField(default=False)),
                ("date_of_birth", models.DateField()),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("height", models.CharField(max_length=20)),
                ("weight", models.CharField(max_length=20)),
                ("shoe_size", models.CharField(max_length=10)),
                (
                    "skin_tone",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("dark", "Dark"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "hair_color",
                    models.CharField(
                        choices=[
                            ("blonde", "Blonde"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                            ("red", "Red"),
                            ("auburn", "Auburn"),
                            ("dirty_blonde", "Dirty Blonde"),
                            ("strawberry_blonde", "Strawberry Blonde"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "body_type_male",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("short_thin", "Short & Thin"),
                            ("short_broad", "Short & Broad"),
                            ("athletic", "Athletic/Average"),
                            ("tall_slim", "Tall & Slim"),
                            ("big_tall", "Big & Tall"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "body_type_female",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petite", "Petite"),
                            ("tall_slender", "Tall & Slender"),
                            ("athletic", "Athletic/Average"),
                            ("curvy", "Curvy"),
                            ("plus_size", "Plus Size"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributor_profile",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
