# Generated by Django 5.2.4 on 2025-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_body_type_female_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributorprofile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
