# Generated by Django 5.2.4 on 2025-08-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_contributorprofile_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributorprofile",
            name="is_admin",
        ),
    ]
